### ISSUE TITLE
import-ssfn.js stuck

### ISSUE THREAD

**Issue by bobjane** [alvinl/auto-trader#2]
Sorry for the probably silly question. I'm completely new to this.

I'm trying to create a sentry file using Steam's ssfn. Executing the following command I get a > followed by a blinking cursor.

> Name@Name-PC ~/stem (master)
> $ node node_module/auto-trader/scripts/import-ssfn.js steamloginname C:\Steam\
> > _

Nothing further happens. If I hit any keys it returns the following error:

> Name@Name-PC ~/stem (master)
> $ node node_module/auto-trader/scripts/import-ssfn.js steamloginname C:\Steam\
> >
> Importing hash for steamloginname and saving to c:\Users\Name\stem/.steamloginname
> Failed to import ssfn: EISDIR, read

**Comment by bobjane** [comment]
Got around it by using BP automatic to create a shaSentryfile then using import-hash.

Working great now, thanks so much.

**Comment by alvinl** [comment]
Should be fixed via ad2102459cfc41f95f6905d073b97c44005a098d
