### ISSUE TITLE
CSGO

### ISSUE THREAD

**Issue by reesev** [alvinl/auto-trader#5]
How can I use this for csgo? I dont play tf2 and looks like i need to play the game to craft metals or get metals. 

Would be great if i could trade cases.

Point me in the right direction and I am sure I can make the edits.

**Comment by alvinl** [comment]
I plan on adding multiple inventory support sometime this weekend but until then you can replace the file `node_modules/auto-trader/handlers/sessionStart.js` with this [one](https://gist.github.com/alvinl/5fe919bdfcd2dcb3765f). It'll only trade cases (and sticker capsules).

**Comment by reesev** [comment]
yea i figured it out after typing that out...  now i just gotta get this
steam to compile on a windows machine and I am good!

**Comment by alvinl** [comment]
kk, just let me know if there's anything else I can help you with. I'll keep this issue open till I release multiple inventory support.

**Comment by reesev** [comment]
so like alvinl states you have to change the app id.

I also changed this line

var validItemNames = ['Scrap Metal',
                      'Refined Metal',
                      'Reclaimed Metal'];

to

var validItemNames = ['Operation Vanguard Case'];

for the bot I am running.

**Comment by sturadnidge** [comment]
I was about to fork / submit PR for multiple game support... will leave you it :). Great job BTW!

**Comment by alvinl** [comment]
Thanks!
