### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by bensegal2034** [alvinl/auto-trader#7]
Hey,

I just installed this and am getting the following error when I try and run the bot.

C:\Users\Ben\stem>node bin/stem auto.json

module.js:340
    throw err;
          ^
Error: Cannot find module 'steam'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Ben\stem\lib\index.js:13:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

C:\Users\Ben\stem>node bin/stem auto2.json

module.js:340
    throw err;
          ^
Error: Cannot find module 'steam'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Ben\stem\lib\index.js:13:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

C:\Users\Ben\stem>

Any help would be appreciated. Thanks!

**Comment by alvinl** [comment]
It's missing the `steam` module, try running `npm install` (while inside the `stem` folder) and then start the bots.

**Comment by bensegal2034** [comment]
Thanks for the quick response!

When I do npm install (when inside of the stem folder, it seems to work okay, but I still get the same exact error mentioned above on running the bots. This however is the log I get when I type npm install (inside of stem folder).

Microsoft Windows [Version 6.3.9600](c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Ben>cd stem

C:\Users\Ben\stem>npm install

## npm WARN package.json steam-trade@0.2.4 No repository field.

> ursa@0.8.1 install C:\Users\Ben\stem\node_modules\steam\node_modules\ursa
> node-gyp configure && node-gyp build && node install.js

C:\Users\Ben\stem\node_modules\steam\node_modules\ursa>node "C:\Program Files\no
dejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp
.js" configure
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:64:11
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:107:15)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "configure"
gyp ERR! cwd C:\Users\Ben\stem\node_modules\steam\node_modules\ursa
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1

## gyp ERR! not ok

> ref@0.3.5 install C:\Users\Ben\stem\node_modules\steam\node_modules\ref
> node-gyp rebuild

C:\Users\Ben\stem\node_modules\steam\node_modules\ref>node "C:\Program Files\nod
ejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.
js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:64:11
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:107:15)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Ben\stem\node_modules\steam\node_modules\ref
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

> protobuf@0.11.0 install C:\Users\Ben\stem\node_modules\steam\node_modules\prot
> obuf
> node-gyp rebuild

C:\Users\Ben\stem\node_modules\steam\node_modules\protobuf>node "C:\Program File
s\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node
-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:64:11
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:107:15)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Ben\stem\node_modules\steam\node_modules\protobuf
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! ursa@0.8.1 install: `node-gyp configure && node-gyp build && node insta
ll.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ursa@0.8.1 install script.
npm ERR! This is most likely a problem with the ursa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure && node-gyp build && node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ursa
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! cwd C:\Users\Ben\stem
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

C:\Users\Ben\stem>

**Comment by alvinl** [comment]
Looks like `npm install` failed because you don't have Python installed. You can install it by downloading it from [here](https://www.python.org/download/releases/2.7.3/#download).

**Comment by bensegal2034** [comment]
I'm an idiot. Sorry.

I just looked in the install instructions, installed Python, and it works great. Thanks for the support, but again, sorry for wasting your time with something that could've been solved by reading the instructions.

**Comment by alvinl** [comment]
No worries, I'm happy to help out
